from .models import PluginManifest, PluginStatus

BUILTINS = [
    PluginManifest(
        id="zdash-risk-summary",
        name="Risk Summary",
        slug="zdash-risk-summary",
        version="1.0.0",
        description="Provides a concise snapshot of current portfolio risk exposure, including drawdown, volatility, and position concentration across active strategies.",
        author="zDash",
        category="risk",
        status=PluginStatus.approved.value,
        required_features=[],
        required_permissions=["risk_read"],
        config_schema={},
        default_config={},
        entrypoint="builtin://risk-summary",
        safety_level="sandbox",
        source_type="builtin",
        source_ref=None,
        checksum=None,
    ),
    PluginManifest(
        id="zdash-backtest-reporter",
        name="Backtest Reporter",
        slug="zdash-backtest-reporter",
        version="1.0.0",
        description="Generates structured backtest reports with performance metrics, equity curves, and trade-by-trade analysis for any completed strategy simulation.",
        author="zDash",
        category="backtesting",
        status=PluginStatus.approved.value,
        required_features=[],
        required_permissions=["backtest_read"],
        config_schema={},
        default_config={},
        entrypoint="builtin://backtest-reporter",
        safety_level="sandbox",
        source_type="builtin",
        source_ref=None,
        checksum=None,
    ),
    PluginManifest(
        id="zdash-content-calendar",
        name="Content Calendar",
        slug="zdash-content-calendar",
        version="1.0.0",
        description="Displays scheduled content items across social and marketing channels, with status tracking from draft through approved and published.",
        author="zDash",
        category="content",
        status=PluginStatus.approved.value,
        required_features=[],
        required_permissions=["content_read"],
        config_schema={},
        default_config={},
        entrypoint="builtin://content-calendar",
        safety_level="sandbox",
        source_type="builtin",
        source_ref=None,
        checksum=None,
    ),
    PluginManifest(
        id="zdash-scheduler-health",
        name="Scheduler Health",
        slug="zdash-scheduler-health",
        version="1.0.0",
        description="Monitors the health of all scheduled jobs, showing last-run times, success rates, failures, and next scheduled executions.",
        author="zDash",
        category="automation",
        status=PluginStatus.approved.value,
        required_features=[],
        required_permissions=["scheduler_read"],
        config_schema={},
        default_config={},
        entrypoint="builtin://scheduler-health",
        safety_level="sandbox",
        source_type="builtin",
        source_ref=None,
        checksum=None,
    ),
    PluginManifest(
        id="zdash-alert-router",
        name="Alert Router",
        slug="zdash-alert-router",
        version="1.0.0",
        description="Evaluates incoming events and routes alerts to configured channels (Slack, email, webhook) based on severity, source, and tenant routing rules.",
        author="zDash",
        category="notifications",
        status=PluginStatus.approved.value,
        required_features=[],
        required_permissions=["notifications_read"],
        config_schema={},
        default_config={},
        entrypoint="builtin://alert-router",
        safety_level="sandbox",
        source_type="builtin",
        source_ref=None,
        checksum=None,
    ),
    PluginManifest(
        id="zdash-tenant-audit-export",
        name="Tenant Audit Export",
        slug="zdash-tenant-audit-export",
        version="1.0.0",
        description="Exports tenant-scoped audit log records into a downloadable structured file for compliance review. Only runs in dry-run mode by default.",
        author="zDash",
        category="compliance",
        status=PluginStatus.approved.value,
        required_features=[],
        required_permissions=["audit_read", "admin"],
        config_schema={},
        default_config={},
        entrypoint="builtin://tenant-audit-export",
        safety_level="restricted",
        source_type="builtin",
        source_ref=None,
        checksum=None,
    ),
]
