version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zsp-aitool-app
    ports:
    - 3017:3000
    env_file:
    - .env
    depends_on:
    - db
    networks:
    - default
    - proxy
    labels:
    - traefik.enable=true
    - traefik.docker.network=proxy
    - traefik.http.routers.zsp_aitool.rule=Host(`zaiz.zeaz.dev`) || Host(`api-zveo.zeaz.dev`)
    - traefik.http.routers.zsp_aitool.entrypoints=web
    - traefik.http.services.zsp_aitool.loadbalancer.server.port=3000
  db:
    image: postgres:16-alpine
    container_name: zsp-aitool-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: zsp_aitool
    ports:
    - 127.0.0.1:5435:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: null
networks:
  proxy:
    external: true
