receivers:
  filelog:
    include: [/var/log/z-runner/*.log]
    start_at: end
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      network: {}
  prometheus:
    config:
      scrape_configs:
        - job_name: z-runner
          static_configs:
            - targets: ["127.0.0.1:9102"]
processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
exporters:
  otlphttp:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
  logging:
    verbosity: basic
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [memory_limiter, batch]
      exporters: [otlphttp, logging]
    metrics:
      receivers: [hostmetrics, prometheus]
      processors: [memory_limiter, batch]
      exporters: [otlphttp, logging]
