from __future__ import annotations

import re
from dataclasses import dataclass

from github import Github


@dataclass(frozen=True)
class AutoFixPullRequest:
    url: str
    branch: str


def redact_patch_secrets(patch: str) -> str:
    return re.sub(r"(?im)(api_key|token|secret)=.*$", r"\1=REDACTED", patch)


def create_auto_fix_pr(*, token: str, repo_name: str, base_branch: str, patch: str) -> AutoFixPullRequest:
    sanitized_patch = redact_patch_secrets(patch).strip()
    if not sanitized_patch:
        raise ValueError("sanitized patch is empty")

    client = Github(token)
    repo = client.get_repo(repo_name)
    base = repo.get_branch(base_branch)

    branch = f"ai/fix-{base_branch}".replace("/", "-")
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base.commit.sha)
    except Exception:
        pass

    repo.create_file(
        path="AUTO_FIX.patch",
        message="chore(pr-bot): add AI auto-fix patch",
        content=sanitized_patch,
        branch=branch,
    )

    pr = repo.create_pull(
        title="🤖 AI Auto-Fix",
        body="Automated fixes generated by AI reviewer.",
        head=branch,
        base=base_branch,
    )
    return AutoFixPullRequest(url=pr.html_url, branch=branch)
