apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: zwallet-db
  namespace: zwallet
spec:
  numberOfInstances: 3
  volume:
    size: 10Gi
  teamId: zwallet
  postgresql:
    version: "15"
  users:
    zwallet:
      - superuser
      - createdb
  databases:
    zwallet: zwallet
