apiVersion: v1
kind: ConfigMap
metadata:
  name: zdash-config
  namespace: zdash
data:
  APP_ENV: "production"
  PROJECT_NAME: "zDash"
  PORT: "8005"
  CORS_ORIGINS: "[\"http://localhost:3000\", \"https://zdash.zeaz.dev\"]"
  LOG_LEVEL: "INFO"
  DRY_RUN: "true"
  PRODUCTION_SAFETY_LOCK: "true"
