apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: zdash
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: zdash-secrets
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "${POSTGRES_USER}"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
