#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_PATH_DEFAULT="$REPO_ROOT/configs/env/domain.env"

usage() {
  cat <<USAGE
Usage: $(basename "$0") [--domain DOMAIN] [--output PATH] [--yes]

Generate an environment file with edge hostnames for *.zeaz.dev-style deployments.

Options:
  --domain DOMAIN   Base domain (default: zeaz.dev)
  --output PATH     Output env file path (default: configs/env/domain.env)
  --yes             Non-interactive mode; accept defaults and provided flags
  -h, --help        Show this help
USAGE
}

require_non_empty() {
  local value="$1"
  local label="$2"
  if [[ -z "$value" ]]; then
    echo "[error] $label must not be empty" >&2
    exit 1
  fi
}

DOMAIN="zeaz.dev"
OUTPUT_PATH="$OUTPUT_PATH_DEFAULT"
ASSUME_YES="false"

while (($# > 0)); do
  case "$1" in
    --domain)
      DOMAIN="${2:-}"
      shift 2
      ;;
    --output)
      OUTPUT_PATH="${2:-}"
      shift 2
      ;;
    --yes)
      ASSUME_YES="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ "$ASSUME_YES" != "true" ]]; then
  read -r -p "Base domain [${DOMAIN}]: " domain_input
  if [[ -n "$domain_input" ]]; then
    DOMAIN="$domain_input"
  fi

  read -r -p "Output env file [${OUTPUT_PATH}]: " output_input
  if [[ -n "$output_input" ]]; then
    OUTPUT_PATH="$output_input"
  fi
fi

require_non_empty "$DOMAIN" "domain"
require_non_empty "$OUTPUT_PATH" "output path"

DOMAIN="${DOMAIN#.}"
if [[ "$DOMAIN" == *" "* ]]; then
  echo "[error] domain must not contain spaces" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"

cat > "$OUTPUT_PATH" <<ENVVARS
# Generated by scripts/generate-domain-env.sh
BASE_DOMAIN=${DOMAIN}
WILDCARD_DOMAIN=*.${DOMAIN}

API_BASE_URL=https://api.${DOMAIN}
ADMIN_BASE_URL=https://admin.${DOMAIN}
AUTH_BASE_URL=https://auth.${DOMAIN}
AI_BASE_URL=https://ai.${DOMAIN}
CRAWL_BASE_URL=https://crawl.${DOMAIN}
PREDICT_BASE_URL=https://predict.${DOMAIN}
GRAFANA_BASE_URL=https://grafana.${DOMAIN}
KAFKA_BASE_URL=https://kafka.${DOMAIN}
ENVVARS

echo "[ok] wrote domain env file to: $OUTPUT_PATH"
echo "[ok] wildcard scope: *.${DOMAIN}"
