# GitHub Sponsors funding configuration
# Repo/account: cvsz

github: cvsz
patreon: zeazdev

open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: zeazdev
thanks_dev:

custom: []
