#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'
usage() { echo 'Usage: scripts/verify/verify-all.sh [--skip-domain-checks]'; }
skip_domains=false
while (($#)); do case "$1" in --skip-domain-checks) skip_domains=true; shift;; --help|-h) usage; exit 0;; *) usage; exit 2;; esac; done
mkdir -p reports/verify docs/reports
json=reports/verify/latest.json
pass=0; fail=0; warn=0
check() { local name="$1" cmd="$2" level="${3:-fail}"; if bash -lc "$cmd" >/tmp/zeaz-verify.$$ 2>&1; then printf '[PASS] %s\n' "$name"; pass=$((pass+1)); else if [[ "$level" == warn ]]; then printf '[WARN] %s\n' "$name"; warn=$((warn+1)); else printf '[FAIL] %s\n' "$name"; fail=$((fail+1)); fi; fi; }
check node 'command -v node && node --version' warn
check package-manager 'command -v pnpm || command -v npm || command -v yarn || command -v bun' warn
check docker 'command -v docker && docker --version' warn
check docker-compose 'docker compose version' warn
check postgres 'scripts/db/check-postgres.sh' warn
check ports 'scripts/ports/check-port-conflicts.sh'
check cloudflare-config 'scripts/cloudflare/check-cloudflare-config.sh'
check env-template 'test -f .env.example && ! rg -n "(dummy[-]secret|fake[-]token|change[ -]?me|replace[-]me)" .env.example'
if [[ -f .env ]]; then check env-local 'test -f .env' warn; else printf '[WARN] env-local missing .env\n'; warn=$((warn+1)); fi
while IFS=, read -r app path domain port; do [[ "$app" == app ]] && continue; [[ "$app" =~ ^(postgres|redis)$ ]] && continue; check "local-$app" "curl -fsSI -m 2 http://127.0.0.1:$port/ || curl -fsS -m 2 http://127.0.0.1:$port/health" warn; done < <(scripts/ports/list-all-ports.sh)
if ! $skip_domains; then for url in https://zow.zeaz.dev https://api-zcfdash.zeaz.dev https://zcfdash.zeaz.dev https://zoffice.zeaz.dev https://app.zeaz.dev https://ztrader.zeaz.dev https://dash.zeaz.dev https://zaiz.zeaz.dev https://zveo.zeaz.dev https://zsticker.zeaz.dev https://zcino.zeaz.dev https://zlms.zeaz.dev; do check "domain-$url" "curl -fsSI -m 5 $url" warn; done; fi
cat > "$json" <<JSON
{"generated_at":"2026-06-09T00:00:00Z","pass":$pass,"fail":$fail,"warn":$warn}
JSON
cat > docs/reports/VERIFY_ALL_REPORT.md <<MD
# Verify All Report

Generated by \`scripts/verify/verify-all.sh\`.

- Pass: $pass
- Fail: $fail
- Warning: $warn
- JSON output: \`reports/verify/latest.json\`

Warnings are expected when local apps, Docker, Postgres, or public domain routes are not running in this environment.
MD
(( fail == 0 ))
