#!/usr/bin/env bash
set -euo pipefail

DOMAIN="zlinebot.zeaz.dev"
OUT_FILE=".env"
INTERACTIVE="${INTERACTIVE_ENV_SETUP:-0}"
POSITIONAL_ARGS=()

while (($#)); do
  case "$1" in
    --interactive|-i)
      INTERACTIVE="1"
      shift
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

if [[ ${#POSITIONAL_ARGS[@]} -ge 1 ]]; then
  DOMAIN="${POSITIONAL_ARGS[0]}"
fi

if [[ ${#POSITIONAL_ARGS[@]} -ge 2 ]]; then
  OUT_FILE="${POSITIONAL_ARGS[1]}"
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secure secrets" >&2
  exit 1
fi

rand_base64() {
  openssl rand -base64 48 | tr -d '\n'
}

rand_hex() {
  openssl rand -hex 32
}

rand_hex_64() {
  openssl rand -hex 64
}

APP_URL="https://${DOMAIN}"
TIKTOK_REDIRECT_URI="${APP_URL}/api/auth/tiktok/callback"

prompt_value() {
  local label="${1}"
  local default_value="${2}"
  local secret_input="${3:-0}"
  local reply=""
  if [[ "${secret_input}" == "1" ]]; then
    read -r -s -p "${label} [default hidden]: " reply
    echo >&2
  else
    read -r -p "${label} [${default_value}]: " reply
  fi
  if [[ -z "${reply}" ]]; then
    reply="${default_value}"
  fi
  printf '%s' "${reply}"
}

LINE_CHANNEL_SECRET_VALUE="$(rand_hex)"
LINE_CHANNEL_ACCESS_TOKEN_VALUE="$(rand_hex_64)"
LINE_DEFAULT_TENANT_ID_VALUE="demo"
TIKTOK_CLIENT_KEY_VALUE=""
TIKTOK_CLIENT_SECRET_VALUE=""
TIKTOK_WEBHOOK_SECRET_VALUE="$(rand_hex)"
TIKTOK_SHOP_ACCESS_TOKEN_VALUE=""
CLOUDFLARE_TUNNEL_TOKEN_VALUE=""
CLOUDFLARE_API_TOKEN_VALUE=""
CLOUDFLARE_ZONE_ID_VALUE=""

if [[ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]]; then
  CLOUDFLARE_TUNNEL_TOKEN_VALUE="${CLOUDFLARE_TUNNEL_TOKEN}"
elif [[ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]]; then
  CLOUDFLARE_TUNNEL_TOKEN_VALUE="${CLOUDFLARE_TUNNEL_TOKEN}"
fi

if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  CLOUDFLARE_API_TOKEN_VALUE="${CLOUDFLARE_API_TOKEN}"
fi

if [[ -n "${CLOUDFLARE_ZONE_ID:-}" ]]; then
  CLOUDFLARE_ZONE_ID_VALUE="${CLOUDFLARE_ZONE_ID}"
fi

if [[ "${INTERACTIVE}" == "1" ]]; then
  echo "🧩 Interactive .env setup for Cloudflare, LINE, and TikTok"
  echo "Press Enter to accept the default shown in brackets."
  echo

  CLOUDFLARE_TUNNEL_TOKEN_VALUE="$(prompt_value "Cloudflare tunnel token (CLOUDFLARE_TUNNEL_TOKEN)" "${CLOUDFLARE_TUNNEL_TOKEN_VALUE}" 1)"
  CLOUDFLARE_API_TOKEN_VALUE="$(prompt_value "Cloudflare API token (CLOUDFLARE_API_TOKEN)" "${CLOUDFLARE_API_TOKEN_VALUE}" 1)"
  CLOUDFLARE_ZONE_ID_VALUE="$(prompt_value "Cloudflare Zone ID (CLOUDFLARE_ZONE_ID)" "${CLOUDFLARE_ZONE_ID_VALUE}")"

  LINE_CHANNEL_SECRET_VALUE="$(prompt_value "LINE channel secret (LINE_CHANNEL_SECRET)" "${LINE_CHANNEL_SECRET_VALUE}" 1)"
  LINE_CHANNEL_ACCESS_TOKEN_VALUE="$(prompt_value "LINE channel access token (LINE_CHANNEL_ACCESS_TOKEN)" "${LINE_CHANNEL_ACCESS_TOKEN_VALUE}" 1)"
  LINE_DEFAULT_TENANT_ID_VALUE="$(prompt_value "LINE default tenant ID (LINE_DEFAULT_TENANT_ID)" "${LINE_DEFAULT_TENANT_ID_VALUE}")"

  TIKTOK_CLIENT_KEY_VALUE="$(prompt_value "TikTok client key (TIKTOK_CLIENT_KEY)" "${TIKTOK_CLIENT_KEY_VALUE}")"
  TIKTOK_CLIENT_SECRET_VALUE="$(prompt_value "TikTok client secret (TIKTOK_CLIENT_SECRET)" "${TIKTOK_CLIENT_SECRET_VALUE}" 1)"
  TIKTOK_WEBHOOK_SECRET_VALUE="$(prompt_value "TikTok webhook secret (TIKTOK_WEBHOOK_SECRET)" "${TIKTOK_WEBHOOK_SECRET_VALUE}" 1)"
  TIKTOK_SHOP_ACCESS_TOKEN_VALUE="$(prompt_value "TikTok shop access token (TIKTOK_SHOP_ACCESS_TOKEN)" "${TIKTOK_SHOP_ACCESS_TOKEN_VALUE}" 1)"
fi

if [[ "${INTERACTIVE}" != "1" && -z "${CLOUDFLARE_TUNNEL_TOKEN_VALUE}" ]]; then
  echo "⚠️ CLOUDFLARE_TUNNEL_TOKEN is empty. Export CLOUDFLARE_TUNNEL_TOKEN before deploy or rerun with --interactive." >&2
fi

cat >"${OUT_FILE}" <<EOF_ENV
# Auto-generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NODE_ENV=production
PORT=3000
DOMAIN=${DOMAIN}
APP_URL=${APP_URL}

JWT_SECRET=$(rand_hex_64)
SESSION_SECRET=$(rand_base64)
ENCRYPTION_KEY=$(rand_hex)
TENANT_API_KEY=$(rand_hex)
ML_GRPC_SECRET=$(rand_hex)

DATABASE_URL=postgresql://postgres:postgres@db:5432/zlinebot
POSTGRES_DB=zlinebot
POSTGRES_USER=zlinebot
POSTGRES_PASSWORD=$(rand_hex)

REDIS_URL=redis://redis:6379
REDIS_PASSWORD=$(rand_hex)
KAFKA_PASSWORD=$(rand_hex)
QDRANT_URL=http://qdrant:6333

LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET_VALUE}
LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN_VALUE}
LINE_DEFAULT_TENANT_ID=${LINE_DEFAULT_TENANT_ID_VALUE}
LINE_WEBHOOK_URL=${APP_URL}/webhook/line

TIKTOK_CLIENT_KEY=${TIKTOK_CLIENT_KEY_VALUE}
TIKTOK_CLIENT_SECRET=${TIKTOK_CLIENT_SECRET_VALUE}
TIKTOK_REDIRECT_URI=${TIKTOK_REDIRECT_URI}
TIKTOK_WEBHOOK_SECRET=${TIKTOK_WEBHOOK_SECRET_VALUE}
TIKTOK_SCOPE=user.info.basic
TIKTOK_SHOP_API_BASE_URL=https://open-api.tiktokglobalshop.com
TIKTOK_SHOP_ACCESS_TOKEN=${TIKTOK_SHOP_ACCESS_TOKEN_VALUE}
TIKTOK_WEBHOOK_URL=${APP_URL}/webhook/tiktok

STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=

QUEUE_CONCURRENCY=5
AUTOMATION_WORKER_MODE=external

RATE_LIMIT=100
CORS_ORIGIN=${APP_URL}

# Cloudflare Tunnel
CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN_VALUE}
CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN_VALUE}
CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID_VALUE}
EOF_ENV

chmod 600 "${OUT_FILE}"
if [[ "${INTERACTIVE}" == "1" ]]; then
  echo "✅ Generated ${OUT_FILE} for ${DOMAIN} with interactive Cloudflare/LINE/TikTok values"
else
  echo "✅ Generated ${OUT_FILE} for ${DOMAIN}"
fi
