global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "zdash-backend"
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - backend:8005

  - job_name: "zdash-nginx-health"
    metrics_path: /health
    static_configs:
      - targets:
          - nginx:80
