apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: zwallet-db
  namespace: zwallet
spec:
  teamId: zwallet
  numberOfInstances: 3
  volume:
    size: 10Gi
    storageClass: standard
  users:
    admin:
      - superuser
      - createdb
  databases:
    zwallet: admin
  postgresql:
    version: "16"
    parameters:
      max_connections: "300"
      shared_buffers: 256MB
      wal_level: replica
  patroni:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  allowedSourceRanges:
    - 10.0.0.0/8
