cluster:
  enabled: true
  nodes: 6
  replicas: 1

usePassword: true

persistence:
  enabled: true
  size: 8Gi

podAntiAffinityPreset: hard

redis:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

pdb:
  create: true
  minAvailable: 4
