global:
  enabled: true

injector:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - vault
          topologyKey: kubernetes.io/hostname
  pdb:
    enabled: true
    minAvailable: 2
