tunnel: zdash-example-tunnel-id
credentials-file: /etc/cloudflared/cert.json

ingress:
  - hostname: zzdash.zeaz.dev
    service: http://nginx:80
  - hostname: api-zzdash.zeaz.dev
    service: http://backend:8005
  - service: http_status:404
