export const openApiDocument = {
  openapi: "3.1.0",
  info: { title: "zVEO API Gateway", version: "1.0.0", description: "Queue-first media orchestration API for Veo, Google Flow, and Nano Banana workflows." },
  servers: [{ url: "http://localhost:8080" }],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: { bearerAuth: { type: "http", scheme: "bearer" } },
    schemas: {
      ErrorResponse: { type: "object", required: ["error", "correlationId"], properties: { error: { type: "string" }, correlationId: { type: "string", format: "uuid" } } },
      WorkflowSubmission: { type: "object", required: ["idempotencyKey", "tenantId", "projectId", "createdBy", "renderProvider", "sceneGraph"], properties: { idempotencyKey: { type: "string", minLength: 8 }, tenantId: { type: "string", format: "uuid" }, projectId: { type: "string", format: "uuid" }, createdBy: { type: "string", format: "uuid" }, priority: { type: "integer", minimum: 0, maximum: 100 }, renderProvider: { enum: ["veo", "google_flow", "nano_banana"] }, sceneGraph: { type: "object" } } },
      WorkflowAccepted: { type: "object", required: ["workflowId", "state", "queuedScenes", "correlationId"], properties: { workflowId: { type: "string", format: "uuid" }, state: { type: "string" }, queuedScenes: { type: "integer" }, correlationId: { type: "string", format: "uuid" } } },
      PipelineCommand: { type: "object", required: ["commandId", "workflowId", "tenantId", "idempotencyKey", "renderArtifacts", "exportProfiles", "requestedBy"], properties: { commandId: { type: "string", format: "uuid" }, workflowId: { type: "string", format: "uuid" }, tenantId: { type: "string", format: "uuid" }, idempotencyKey: { type: "string", minLength: 8 }, renderArtifacts: { type: "array", minItems: 1, items: { type: "object" } }, exportProfiles: { type: "array", minItems: 1, items: { type: "object", required: ["platform", "width", "height", "videoBitrateKbps"], properties: { platform: { enum: ["youtube", "tiktok", "instagram_reels", "x", "linkedin", "broadcast", "archive"] }, width: { type: "integer" }, height: { type: "integer" }, videoBitrateKbps: { type: "integer" } } } }, beatMarkers: { type: "array", items: { type: "object" } }, subtitleCues: { type: "array", items: { type: "object" } }, requestedBy: { type: "string", format: "uuid" } } },
      PipelinePlan: { type: "object", required: ["workflowId", "tenantId", "commandId", "stages", "checkpoints", "ffmpegFilterGraph", "exportManifests"], properties: { workflowId: { type: "string", format: "uuid" }, tenantId: { type: "string", format: "uuid" }, commandId: { type: "string", format: "uuid" }, stages: { type: "array", items: { type: "string" } }, checkpoints: { type: "array", items: { type: "object" } }, ffmpegFilterGraph: { type: "string" }, exportManifests: { type: "array", items: { type: "object" } } } },
      OpsSummary: { type: "object", required: ["status", "correlationId", "queue", "workers"], properties: { status: { type: "string" }, correlationId: { type: "string", format: "uuid" }, queue: { type: "object", required: ["waiting", "active", "delayed", "completed", "failed"], properties: { waiting: { type: "integer", minimum: 0 }, active: { type: "integer", minimum: 0 }, delayed: { type: "integer", minimum: 0 }, completed: { type: "integer", minimum: 0 }, failed: { type: "integer", minimum: 0 } } }, workers: { type: "object", required: ["onlineEstimate", "heartbeatTtlMs"], properties: { onlineEstimate: { type: "integer", minimum: 0 }, heartbeatTtlMs: { type: "integer", minimum: 1 } } } } },
      PublishJob: { type: "object", required: ["id", "tenantId", "workflowId", "assetId", "targetId", "provider", "state", "caption", "createdAt", "updatedAt"], properties: { id: { type: "string", format: "uuid" }, tenantId: { type: "string", format: "uuid" }, workflowId: { type: "string", format: "uuid" }, assetId: { type: "string", format: "uuid" }, targetId: { type: "string", format: "uuid" }, provider: { type: "string", enum: ["facebook"] }, state: { type: "string" }, caption: { type: "string" }, remotePostId: { type: "string" }, remoteVideoId: { type: "string" }, lastError: { type: "string" }, createdAt: { type: "string" }, updatedAt: { type: "string" } } },
      Metrics: { type: "string" }
    }
  },
  paths: {
    "/healthz": { get: { security: [], responses: { "200": { description: "service health" } } } },
    "/readyz": { get: { security: [], responses: { "200": { description: "dependency readiness" } } } },
    "/metrics": { get: { security: [], responses: { "200": { description: "Prometheus metrics", content: { "text/plain": { schema: { $ref: "#/components/schemas/Metrics" } } } } } } },
    "/openapi.json": { get: { security: [], responses: { "200": { description: "OpenAPI document" } } } },
    "/v1/ops/summary": { get: { summary: "Get operational queue and worker summary", responses: { "200": { description: "Operational summary", content: { "application/json": { schema: { $ref: "#/components/schemas/OpsSummary" } } } }, "503": { description: "Queue unavailable", content: { "application/json": { schema: { $ref: "#/components/schemas/OpsSummary" } } } } } } },
    "/v1/workflows": { post: { summary: "Submit a render workflow", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/WorkflowSubmission" } } } }, responses: { "202": { description: "Workflow accepted", content: { "application/json": { schema: { $ref: "#/components/schemas/WorkflowAccepted" } } } }, "400": { description: "Validation error" }, "401": { description: "Authentication error" }, "403": { description: "Authorization error" } } } },
    "/v1/workflows/{workflowId}/media-pipelines": { post: { summary: "Plan a resumable media export pipeline", parameters: [{ name: "workflowId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/PipelineCommand" } } } }, responses: { "202": { description: "Pipeline planned", content: { "application/json": { schema: { $ref: "#/components/schemas/PipelinePlan" } } } }, "400": { description: "Validation error" }, "401": { description: "Authentication error" }, "403": { description: "Authorization error" } } } }
    ,"/v1/publish/facebook/videos": { post: { summary: "Publish rendered video to a Facebook Page target", responses: { "202": { description: "Publish accepted" } } } }
    ,"/v1/publish/{publishJobId}": { get: { summary: "Get publish job status", parameters: [{ name: "publishJobId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Publish job", content: { "application/json": { schema: { type: "object", properties: { publishJob: { $ref: "#/components/schemas/PublishJob" }, correlationId: { type: "string", format: "uuid" } } } } } } } } }
  }
} as const;
