<?php
$gameid = $_GET['id'];
include('../includes/connection.inc.php');
$path = mysqli_fetch_array(mysqli_query($GLOBALS['con'],"SELECT `location`,`base_directory` FROM `cws_games` WHERE `id`='$gameid'"));

if (file_exists($_SERVER['DOCUMENT_ROOT'].'/'.$path['location'])) {
?>function embedswfile(target, swf, base, width, height) {d = '<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="'+width+'" height="' + height + '" id="mapcontrols">'+'<param name="movie" value="' + swf+'">'+'<param name="quality" value="high">'+'<param name="menu" value="false">'+'<param name="base" value="' + base + '">' +
'<embed src="'+swf+'" menu="false" swLiveConnect="true" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="' + width + '" height="' + height + '" name="mapcontrols" base="' + base + '">'+'</embed>'+'</object>'};function embedSwf(target, swf, base, width, height) {d = document.getElementById( target );d.innerHTML = '<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="'+width+'" height="' + height + '" id="mapcontrols">'+'<param name="movie" value="' + swf+'">'+'<param name="quality" value="high">'+'<param name="menu" value="false">'+'<param name="allowFullScreen" value="true">'+'<param name="base" value="' + base + '">' +
'<embed src="'+swf+'" menu="false" swLiveConnect="true" allowFullScreen="true" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="' + width + '" height="' + height + '" name="mapcontrols" base="' + base + '">'+'</embed>'+'</object>';
}$(document).ready(function(){md5_decode("<?=base64_encode($path['location'])?>", function(location) {md5_decode("<?=base64_encode($path['base_directory'])?>", function(dir){embedSwf("flashgame",location,dir,"800","600" );});});});<?php }else {?>function embedswfile(target, swf, base, width, height) {d = document.getElementById( target );d.innerHTML = '<div style="color:red;text-align:center;font-weight:bold;font-size:26px;padding-top:35px;height:180px;width:640px;">Game not available</div>';}function embedSwf(target, swf, base, width, height) {d = document.getElementById( target );d.innerHTML = '<div style="color:red;text-align:center;font-weight:bold;font-size:26px;padding-top:35px;height:180px;width:640px;">Game not available</div>';}<?php }?>