name: security-scanning
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: cloudflare-platform/terraform
      - name: Trivy IaC
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: config
          scan-ref: cloudflare-platform/terraform
