name: terraform-apply
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: dev
jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=cloudflare-platform/terraform/envs/${{ github.event.inputs.environment }} init -input=false
      - run: terraform -chdir=cloudflare-platform/terraform/envs/${{ github.event.inputs.environment }} apply -auto-approve
