# infra/nginx/modsecurity.conf
# Enable ModSecurity with OWASP CRS

LoadModule security2_module modules/modsecurity.so

<IfModule security2_module>
    SecRuleEngine On
    SecRequestBodyAccess On
    SecResponseBodyAccess Off

    Include /etc/modsecurity/crs/crs-setup.conf
    Include /etc/modsecurity/crs/rules/*.conf
</IfModule>
