services:
  litellm:
    extends:
      file: ../litellm/docker-compose.yaml
      service: litellm
  ai-runtime:
    depends_on:
      litellm:
        condition: service_healthy
    environment:
      - AI_PROXY_URL=http://litellm:4000