"""phase10_models

Revision ID: 7054888e2a84
Revises: 20260524_0003
Create Date: 2026-05-28 04:32:38.025696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7054888e2a84'
down_revision: Union[str, None] = '20260524_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _dialect_name() -> str:
    return op.get_bind().dialect.name


def _table_exists(table_name: str) -> bool:
    return bool(sa.inspect(op.get_bind()).has_table(table_name))


def _column_exists(table_name: str, column_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    columns = sa.inspect(op.get_bind()).get_columns(table_name)
    return any(column["name"] == column_name for column in columns)


def _index_exists(table_name: str, index_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    indexes = sa.inspect(op.get_bind()).get_indexes(table_name)
    return any(index["name"] == index_name for index in indexes)


def _add_column_once(table_name: str, column: sa.Column) -> None:
    if not _column_exists(table_name, column.name):
        op.add_column(table_name, column)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists('refresh_tokens'):
        with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_refresh_tokens_token_hash'), ['token_hash'])
            batch_op.create_foreign_key(batch_op.f('fk_refresh_tokens_user_id_users'), 'users', ['user_id'], ['id'])

    # SQLite-safe/idempotent scheduler_jobs migration.
    # Avoid Alembic batch table recreation here because SQLite can raise
    # CircularDependencyError when adding multiple columns and altering
    # interval_seconds in one batch.
    if _table_exists('scheduler_jobs'):
        _add_column_once(
            'scheduler_jobs',
            sa.Column('job_type', sa.String(), nullable=False, server_default='custom'),
        )
        _add_column_once(
            'scheduler_jobs',
            sa.Column('schedule_type', sa.String(), nullable=False, server_default='interval'),
        )
        _add_column_once(
            'scheduler_jobs',
            sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
        )
        _add_column_once(
            'scheduler_jobs',
            sa.Column('cron', sa.String(), nullable=True),
        )
        _add_column_once(
            'scheduler_jobs',
            sa.Column('payload', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        )

        if _dialect_name() != 'sqlite':
            op.alter_column(
                'scheduler_jobs',
                'interval_seconds',
                existing_type=sa.INTEGER(),
                nullable=True,
            )

        if not _index_exists('scheduler_jobs', 'ix_scheduler_jobs_name'):
            op.create_index('ix_scheduler_jobs_name', 'scheduler_jobs', ['name'], unique=False)

    # SQLite-safe/idempotent users migration.
    # Some CI/test databases may already have the current users schema,
    # while older baseline databases may still include username.
    if _table_exists('users'):
        _add_column_once(
            'users',
            sa.Column('email', sa.String(), nullable=False, server_default=''),
        )
        _add_column_once(
            'users',
            sa.Column('display_name', sa.String(), nullable=False, server_default=''),
        )
        _add_column_once(
            'users',
            sa.Column(
                'updated_at',
                sa.DateTime(timezone=True),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            ),
        )

        if not _index_exists('users', 'ix_users_email'):
            op.create_index('ix_users_email', 'users', ['email'], unique=True)

        # Avoid SQLite batch/drop-column edge cases in CI. The ORM ignores
        # legacy username if it exists, and production databases can drop it
        # safely on non-SQLite dialects.
        if _column_exists('users', 'username') and _dialect_name() != 'sqlite':
            op.drop_column('users', 'username')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('display_name')
        batch_op.drop_column('email')

    with op.batch_alter_table('scheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduler_jobs_name'))
        batch_op.alter_column('interval_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('payload')
        batch_op.drop_column('cron')
        batch_op.drop_column('enabled')
        batch_op.drop_column('schedule_type')
        batch_op.drop_column('job_type')

    if _table_exists('refresh_tokens'):
        with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('fk_refresh_tokens_user_id_users'), type_='foreignkey')
            batch_op.drop_constraint(batch_op.f('uq_refresh_tokens_token_hash'), type_='unique')

    # ### end Alembic commands ###
