#!/usr/bin/env python3
from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

ROOT = Path.cwd()
CONFIG = ROOT / "configs/repos/cvsz-apps-merge-map.json"
REPORT = ROOT / "docs/reports/generated/cvsz-apps-merge-plan.md"
JSON_OUT = ROOT / "generated/integration/cvsz-apps-merge-plan.json"


def run(cmd: list[str], cwd: Path = ROOT) -> str:
    try:
        return subprocess.check_output(cmd, cwd=str(cwd), stderr=subprocess.DEVNULL, text=True).strip()
    except Exception:
        return ""


def repo_reachable(repo: str) -> bool:
    return bool(run(["git", "ls-remote", "--heads", repo]))


def app_info(app: dict[str, Any]) -> dict[str, Any]:
    target = ROOT / app["target_path"]
    nested_git = (target / ".git").exists()
    root_tracked = len(run(["git", "ls-files", "--", app["target_path"]]).splitlines())
    status = run(["git", "status", "--short", "--", app["target_path"]]).splitlines()
    origin = run(["git", "-C", str(target), "remote", "get-url", "origin"]) if nested_git else ""
    branch = run(["git", "-C", str(target), "branch", "--show-current"]) if nested_git else ""
    head = run(["git", "-C", str(target), "rev-parse", "--short", "HEAD"]) if nested_git else ""

    blockers: list[str] = []
    warnings: list[str] = []

    if not target.exists():
        blockers.append("target path missing")
    if nested_git and root_tracked > 0:
        blockers.append("nested git exists while files are already tracked by root")
    if status:
        warnings.append("root git status has changes under app path")
    if nested_git and origin and origin != app["repo"]:
        warnings.append(f"nested origin differs: {origin}")
    if app["mode"] == "already-integrated" and nested_git:
        blockers.append("already-integrated app must not contain nested .git")

    local_envs = []
    if target.exists():
        for p in target.rglob(".env*"):
            if any(part in {".git", "node_modules", ".venv"} for part in p.parts):
                continue
            if "example" not in p.name:
                local_envs.append(str(p.relative_to(ROOT)))
    if local_envs:
        warnings.append("local env files exist and must remain untracked")

    return {
        **app,
        "exists": target.exists(),
        "nested_git": nested_git,
        "root_tracked_files": root_tracked,
        "root_status": status,
        "nested_origin": origin,
        "nested_branch": branch,
        "nested_head": head,
        "repo_reachable": repo_reachable(app["repo"]),
        "local_env_files": local_envs,
        "blockers": blockers,
        "warnings": warnings,
    }


def main() -> int:
    config = json.loads(CONFIG.read_text())
    apps = [app_info(app) for app in config["apps"]]

    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps({"apps": apps}, indent=2) + "\n")

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# cvsz apps merge plan",
        "",
        "Generated by `scripts/apps/plan-cvsz-apps-merge.py`.",
        "",
        "## Summary",
        "",
        "| App | Mode | Exists | Nested Git | Root Tracked | Repo Reachable | Blockers | Warnings |",
        "|---|---|---:|---:|---:|---:|---|---|",
    ]

    for app in apps:
        lines.append(
            "| {app_id} | {mode} | {exists} | {nested_git} | {root_tracked_files} | {repo_reachable} | {blockers} | {warnings} |".format(
                app_id=app["app_id"],
                mode=app["mode"],
                exists=str(app["exists"]),
                nested_git=str(app["nested_git"]),
                root_tracked_files=app["root_tracked_files"],
                repo_reachable=str(app["repo_reachable"]),
                blockers="<br>".join(app["blockers"]) or "-",
                warnings="<br>".join(app["warnings"]) or "-",
            )
        )

    lines += [
        "",
        "## Recommended merge order",
        "",
        "1. P0: keep `apps/zdash` stable and tracked.",
        "2. P1: deep-dive and adopt `apps/ABTPi18n` and `apps/zkbtrader`.",
        "3. P2: adopt product apps with clear runtime boundaries.",
        "4. P3: adopt legacy/static apps after generated files are excluded.",
        "",
        "## Apply rules",
        "",
        "- Apply requires `APPLY=true CONFIRM_CVSZ_APPS_MERGE=yes`.",
        "- Apply must not commit automatically.",
        "- Remove nested `.git` only after `IMPORT_SOURCE.md` is written.",
        "- Keep local env/state/build/cache files untracked.",
    ]

    REPORT.write_text("\n".join(lines) + "\n")
    print(f"PASS: wrote {REPORT}")
    print(f"PASS: wrote {JSON_OUT}")

    hard_blockers = [a for a in apps if a["blockers"]]
    if hard_blockers:
        print("WARN: blockers found; inspect report before apply")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
