tunnel: ${CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/${CLOUDFLARE_TUNNEL_ID}.json
metrics: 127.0.0.1:2000
no-autoupdate: true
ingress:
  - hostname: zow.zeaz.dev
    service: http://localhost:4101
  - hostname: api-zcfdash.zeaz.dev
    service: http://localhost:4102
  - hostname: zcfdash.zeaz.dev
    service: http://localhost:4103
  - hostname: zoffice.zeaz.dev
    service: http://localhost:4104
  - hostname: app.zeaz.dev
    service: http://localhost:4105
  - hostname: ztrader.zeaz.dev
    service: http://localhost:4106
  - hostname: dash.zeaz.dev
    service: http://localhost:4107
  - hostname: zaiz.zeaz.dev
    service: http://localhost:4108
  - hostname: zveo.zeaz.dev
    service: http://localhost:4109
  - hostname: zsticker.zeaz.dev
    service: http://localhost:4110
  - hostname: zcino.zeaz.dev
    service: http://localhost:4111
  - hostname: zlms.zeaz.dev
    service: http://localhost:4112
  - service: http_status:404
