records:
  - name: "zlinebot.zeaz.dev"
    type: CNAME
    value: <tunnel-id>.cfargotunnel.com
    proxied: true
  - name: "*.zeaz.dev"
    type: CNAME
    value: <tunnel-id>.cfargotunnel.com
    proxied: true
