apiVersion: v1
kind: Secret
metadata:
  name: zdash-secrets
  namespace: zdash
type: Opaque
data:
  POSTGRES_USER: "PG_USER_BASE64_PLACEHOLDER"
  POSTGRES_PASSWORD: "PG_PASSWORD_BASE64_PLACEHOLDER"
  SECRET_KEY: "SECRET_KEY_BASE64_PLACEHOLDER"
  ENCRYPTION_KEY: "ENCRYPTION_KEY_BASE64_PLACEHOLDER"
