apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment
  labels:
    app: payment-service
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: payment-service
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: payment
        image: zacademy/payment:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8084
        - name: metrics
          containerPort: 9090
        env:
        - name: ENVIRONMENT
          value: prod
        - name: AWS_REGION
          value: us-east-1
        - name: OTEL_SERVICE_NAME
          value: payment-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.observability.svc.cluster.local:4317
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.15"
        - name: MARQETA_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: marqeta_app_token
        - name: MARQETA_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: marqeta_access_token
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: webhook_secret
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "2"
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /livez
            port: http
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
