apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-secrets
  namespace: payment
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: payment-secrets
    creationPolicy: Owner
  data:
  - secretKey: marqeta_app_token
    remoteRef:
      key: zacademy-prod-payment/api
      property: marqeta_app_token
  - secretKey: marqeta_access_token
    remoteRef:
      key: zacademy-prod-payment/api
      property: marqeta_access_token
  - secretKey: webhook_secret
    remoteRef:
      key: zacademy-prod-payment/api
      property: webhook_secret
