apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: payment
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/zacademy-prod-payment-workload
