#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

# Safe writer for Cloudflare env file
# Usage:
#   CLOUDFLARE_ACCOUNT_ID=... CLOUDFLARE_ZONE_ID=... ./write-env.sh [output-file]
# If no output-file provided, defaults to .env.cloudflare

OUTPUT_FILE="${1:-.env.cloudflare}"
LOG_FILE="/tmp/zveo-cf-env.log"

exec > >(tee -a "$LOG_FILE") 2>&1

: "${CLOUDFLARE_ACCOUNT_ID:?Missing CLOUDFLARE_ACCOUNT_ID}"
: "${CLOUDFLARE_ZONE_ID:?Missing CLOUDFLARE_ZONE_ID}"

# Optional tokens may be empty
CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN:-}"
CLOUDFLARE_DNS_TOKEN="${CLOUDFLARE_DNS_TOKEN:-}"
CLOUDFLARE_ZT_TOKEN="${CLOUDFLARE_ZT_TOKEN:-}"
CLOUDFLARE_WORKERS_TOKEN="${CLOUDFLARE_WORKERS_TOKEN:-}"
CLOUDFLARE_WAF_TOKEN="${CLOUDFLARE_WAF_TOKEN:-}"
CLOUDFLARE_TUNNEL_TOKEN="${CLOUDFLARE_TUNNEL_TOKEN:-}"
CLOUDFLARE_R2_TOKEN="${CLOUDFLARE_R2_TOKEN:-}"

log() {
  printf '[%s] %s\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "$*"
}

log "Writing Cloudflare secrets to ${OUTPUT_FILE}"
touch "${OUTPUT_FILE}"
chmod 600 "${OUTPUT_FILE}"

# Write to a temp file then atomically move
TMP="$(mktemp "${OUTPUT_FILE}.XXXXXX")"
chmod 600 "${TMP}"

cat > "${TMP}" <<EOF
CLOUDFLARE_ACCOUNT_ID="${CLOUDFLARE_ACCOUNT_ID}"
CLOUDFLARE_ZONE_ID="${CLOUDFLARE_ZONE_ID}"
CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN}"
CLOUDFLARE_DNS_TOKEN="${CLOUDFLARE_DNS_TOKEN}"
CLOUDFLARE_ZT_TOKEN="${CLOUDFLARE_ZT_TOKEN}"
CLOUDFLARE_WORKERS_TOKEN="${CLOUDFLARE_WORKERS_TOKEN}"
CLOUDFLARE_WAF_TOKEN="${CLOUDFLARE_WAF_TOKEN}"
CLOUDFLARE_TUNNEL_TOKEN="${CLOUDFLARE_TUNNEL_TOKEN}"
CLOUDFLARE_R2_TOKEN="${CLOUDFLARE_R2_TOKEN}"
EOF

mv "${TMP}" "${OUTPUT_FILE}"
chmod 600 "${OUTPUT_FILE}"

log "Secrets written to ${OUTPUT_FILE} with permissions 600"
exit 0