#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "${ROOT_DIR}/scripts/cloudflare/cloudflare-api-lib.sh"

ZONE_NAME="${ZONE_NAME:-zeaz.dev}"
ZDASH_FRONTEND_HOST="${ZDASH_FRONTEND_HOST:-zdash.zeaz.dev}"
ZDASH_API_HOST="${ZDASH_API_HOST:-api-zdash.zeaz.dev}"
ZDASH_RELEASE_HOST="${ZDASH_RELEASE_HOST:-release.zeaz.dev}"

REPORT="${ROOT_DIR}/docs/reports/generated/zdash-cloudflare-api-preflight.md"
: >"${REPORT}.tmp"
ENV_OUT="${ROOT_DIR}/.env.cloudflare.zdash.generated"

mkdir -p "${ROOT_DIR}/docs/reports/generated"

cf_cost_lock_check
cf_require_tools
cf_require_token

echo "=== zDash Cloudflare API preflight ==="

zone_id="${TF_VAR_cloudflare_zone_id:-${CLOUDFLARE_ZONE_ID:-}}"

if [[ -n "$zone_id" && "$zone_id" != REPLACE_* ]]; then
  cf_validate_zone_id "$zone_id"
  echo "Using supplied Cloudflare zone id for ${ZONE_NAME}"

  tmp="$(mktemp)"
  if ! cf_api GET "/zones/${zone_id}" >"$tmp"; then
    rm -f "$tmp"
    cf_fail "token cannot read supplied zone id. Required: Zone/Zone Read on zeaz.dev"
  fi

  zone_name_from_api="$(jq -r '.result.name // empty' "$tmp")"
  rm -f "$tmp"

  if [[ "$zone_name_from_api" != "$ZONE_NAME" ]]; then
    cf_fail "supplied zone id does not match ${ZONE_NAME}; got ${zone_name_from_api:-empty}"
  fi
else
  echo "No zone id supplied; trying zone lookup by name"
  zone_id="$(cf_zone_id_by_name "$ZONE_NAME" || true)"
  [[ -n "$zone_id" ]] || cf_fail "could not resolve zone id for ${ZONE_NAME}; set CLOUDFLARE_ZONE_ID or TF_VAR_cloudflare_zone_id"
  cf_validate_zone_id "$zone_id"
fi

tunnel_name="${CLOUDFLARE_TUNNEL_NAME:-${ZDASH_TUNNEL_NAME:-zeaz-platform}}"
account_id="${CLOUDFLARE_ACCOUNT_ID:-${TF_VAR_cloudflare_account_id:-}}"
tunnel_id="${TF_VAR_cloudflare_tunnel_id:-${CLOUDFLARE_TUNNEL_ID:-}}"

if [[ -z "$tunnel_id" || "$tunnel_id" == REPLACE_* ]]; then
  if [[ -n "$account_id" ]]; then
    echo "Trying Cloudflare API tunnel lookup by name: ${tunnel_name}"
    tunnel_id="$(cf_tunnel_id_by_name "$account_id" "$tunnel_name" || true)"

    if [[ -z "$tunnel_id" ]]; then
      echo "Tunnel name ${tunnel_name} not found; selecting first active/healthy tunnel from account"
      tunnel_id="$(cf_tunnel_id_first_healthy "$account_id" || true)"
    fi

    {
      echo
      echo "## Tunnels visible to token"
      echo
      cf_tunnel_list_report "$account_id" | sed 's/^/- /' || true
    } >>"$REPORT.tmp"
  fi
fi

if [[ -z "$tunnel_id" || "$tunnel_id" == REPLACE_* ]]; then
  if command -v cloudflared >/dev/null 2>&1; then
    echo "Trying local cloudflared tunnel list"
    tunnel_id="$(cloudflared tunnel list 2>/dev/null | awk 'NR>1 && $1 ~ /^[0-9a-fA-F-]{36}$/ {print $1; exit}' || true)"
  fi
fi

[[ -n "$tunnel_id" ]] || cf_fail "could not resolve tunnel UUID; set CLOUDFLARE_TUNNEL_ID, TF_VAR_cloudflare_tunnel_id, or CLOUDFLARE_TUNNEL_NAME"
cf_validate_tunnel_uuid "$tunnel_id"

frontend_id="$(cf_dns_record_id "$zone_id" "$ZDASH_FRONTEND_HOST" || true)"
api_id="$(cf_dns_record_id "$zone_id" "$ZDASH_API_HOST" || true)"
release_id="$(cf_dns_record_id "$zone_id" "$ZDASH_RELEASE_HOST" || true)"

{
  echo "# zDash Cloudflare API Preflight"
  echo
  echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "- zone_name: ${ZONE_NAME}"
  echo "- zone_id: ${zone_id}"
  echo "- tunnel_id: ${tunnel_id}"
  echo "- tunnel_target: ${tunnel_id}.cfargotunnel.com"
  echo
  echo "## DNS records"
  echo
  echo "- ${ZDASH_FRONTEND_HOST}: ${frontend_id:-MISSING}"
  echo "- ${ZDASH_API_HOST}: ${api_id:-MISSING}"
  echo "- ${ZDASH_RELEASE_HOST}: ${release_id:-MISSING}"
  echo
  echo "## Terraform import commands"
  [[ -n "$frontend_id" ]] && echo "terraform import 'cloudflare_dns_record.zdash[\"zdash_frontend\"]' '${zone_id}/${frontend_id}'"
  [[ -n "$api_id" ]] && echo "terraform import 'cloudflare_dns_record.zdash[\"zdash_api\"]' '${zone_id}/${api_id}'"
  [[ -n "$release_id" ]] && echo "terraform import 'cloudflare_dns_record.zdash[\"zdash_release\"]' '${zone_id}/${release_id}'"
  cat "${REPORT}.tmp" 2>/dev/null || true
} >"$REPORT"
rm -f "${REPORT}.tmp"

cat >"$ENV_OUT" <<EOF_ENV
# Generated by zdash-cloudflare-preflight.sh
# Local-only. Do not commit.
COST_LOCK=true
CLOUDFLARE_PLAN_TIER=Free
ALLOW_PAID_CLOUDFLARE_FEATURES=false
ALLOW_LOAD_BALANCING=false
ALLOW_ADVANCED_WAF=false
ALLOW_LOGPUSH=false
ALLOW_R2_WRITE=false
ALLOW_WORKERS_DEPLOY=false

TF_VAR_cloudflare_zone_id=${zone_id}
TF_VAR_cloudflare_tunnel_id=${tunnel_id}
TF_VAR_zdash_domain=${ZDASH_FRONTEND_HOST}
TF_VAR_zdash_api_domain=${ZDASH_API_HOST}
TF_VAR_zdash_release_domain=${ZDASH_RELEASE_HOST}
EOF_ENV

chmod 600 "$ENV_OUT"

echo "PASS: Cloudflare preflight complete"
echo "Report: $REPORT"
echo "Env: $ENV_OUT"
