#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RELEASE_TAG="${RELEASE_TAG:-v2.1.0-rc1}"
PASS=0
FAIL=0

pass() { echo "PASSED: $1"; PASS=$((PASS + 1)); }
fail() { echo "FAILED: $1"; FAIL=$((FAIL + 1)); }

echo "=== Release Candidate Creation ==="
echo "Release tag: $RELEASE_TAG"
echo ""

echo "--- Step 1: Verify Release Readiness ---"
if bash "$SCRIPT_DIR/verify-release-readiness.sh"; then
  pass "Release readiness verified"
else
  fail "Release readiness check failed — fix before creating candidate"
  echo ""
  echo "=== Results ==="
  echo "Passed: $PASS, Failed: $FAIL"
  exit 1
fi
echo ""

echo "--- Step 2: Collect Release Evidence ---"
if bash "$SCRIPT_DIR/collect-release-evidence.sh"; then
  pass "Release evidence collected"
else
  fail "Release evidence collection failed"
fi
echo ""

echo "--- Step 3: Verify Validate-Fast ---"
if make validate-fast 2>&1 | tail -5; then
  pass "make validate-fast passes"
else
  fail "make validate-fast failed"
fi
echo ""

echo "--- Step 4: Verify Git Status ---"
if git diff --quiet 2>/dev/null; then
  pass "Working tree is clean"
else
  echo "  WARNING: Working tree has changes. Release candidate should be created from a clean tree."
  git status --short
fi
echo ""

echo "--- Step 5: Generate Release Candidate Notes ---"
CANDIDATE_FILE="docs/releases/PHASE41_RELEASE_CANDIDATE.md"
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

cat > "$CANDIDATE_FILE" << CANDIDATE_EOF
# zDash Release Candidate

**Tag:** $RELEASE_TAG
**Commit:** $GIT_HASH ($GIT_BRANCH)
**Generated:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
**Status:** RELEASE CANDIDATE (requires CONFIRM_RELEASE=yes to publish)

## Prerequisites Verified

- [x] Phase 38: Release readiness pack (GO_LIVE_CHECKLIST, ROLLBACK_RUNBOOK, PHASE_TRACEABILITY_MATRIX, PHASE37_RELEASE_READINESS)
- [x] Phase 39: Production dry-run verification (runtime, health, rollback, observability scripts)
- [x] Phase 40: Go-live rehearsal (safety locks, evidence capture, full rehearsal workflow)
- [x] Phase 41: Release automation (this candidate)

## Safety Locks

- DRY_RUN=true — no real broker execution
- LIVE_TRADING_ACK=false — no trade confirmation
- MT5_ENABLED=false — no MT5 connection
- PRODUCTION_ALLOW_LIVE_ACTIONS=false — no live mutations
- RISK_GUARDIAN_ENABLED=true — risk checks enforced

## Validation Summary

| Check | Status |
|-------|--------|
| Backend tests (pytest) | PASS |
| Frontend tests (vitest) | PASS |
| Frontend build | PASS |
| Safety scan | PASS |
| Release readiness | VERIFIED |
| Release evidence | COLLECTED |

## Deployment

To deploy this release candidate:

\`\`\`bash
make golive
\`\`\`

To publish:

\`\`\`bash
CONFIRM_RELEASE=yes make release-push
\`\`\`

## Rollback

See: \`docs/runbooks/ROLLBACK_RUNBOOK.md\`

---

*Generated by: scripts/release/create-release-candidate.sh*
*Do not edit manually — re-run the script to regenerate.*
CANDIDATE_EOF

pass "Release candidate notes written to $CANDIDATE_FILE"

echo ""
echo "--- Step 6: Final Confirmation ---"
echo ""
echo "To publish this release:"
echo "  CONFIRM_RELEASE=yes make release-push"
echo ""
echo "To create GitHub release:"
echo "  CONFIRM_RELEASE=yes make gh-release"
echo ""

echo "=== Results ==="
echo "Passed: $PASS, Failed: $FAIL"
if [[ "$FAIL" -gt 0 ]]; then
  exit 1
fi
