apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zveo-prod
resources:
  - ../base
  - namespace.yaml
  - ingress.yaml
  - observability.yaml
images:
  - name: ghcr.io/example/zveo-api-gateway
    newName: ghcr.io/zveo/api-gateway
    newTag: 1.0.0
  - name: ghcr.io/example/zveo-render-worker
    newName: ghcr.io/zveo/render-worker
    newTag: 1.0.0
patches:
  - path: patches.yaml
