name: Terraform (Reusable)

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infra/
      - name: Terraform Init
        run: terraform init
        working-directory: infra/
      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/
      - name: Terraform Plan
        if: ${{ inputs.command == 'plan' }}
        run: terraform plan
        working-directory: infra/
