allowBuilds:
  '@whiskeysockets/baileys': true
  better-sqlite3: true
  electron: true
  esbuild: true
  msgpackr-extract: true
  msw: false
  node-pty: true
  protobufjs: true
  sharp: true
catalog:
  react: 19.2.4
  react-dom: 19.2.4
catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
linkWorkspacePackages: true
minimumReleaseAge: 0
minimumReleaseAgeExclude:
- '@opencode-ai/sdk'
overrides:
  '@opentelemetry/exporter-prometheus': latest
  '@opentelemetry/sdk-node': latest
  '@protobufjs/utf8': latest
  '@tootallnate/once': latest
  axios: latest
  defu: latest
  diff: latest
  esbuild: 0.28.1
  fast-uri: latest
  fast-xml-parser: latest
  file-type: latest
  follow-redirects: latest
  ip-address: latest
  next: latest
  postcss: 8.5.15
  protobufjs: latest
  qs: latest
  react-router: latest
  rollup: latest
  samlify: latest
  seroval: latest
  shell-quote: 1.8.4
  tar: latest
  tmp: latest
  uuid: latest
  ws: latest
  yaml: latest
packages:
- apps/*
- packages/*
- ee/apps/*
- ee/packages/*
preferWorkspacePackages: true
