minimumReleaseAge: 4320
minimumReleaseAgeExclude:
- '@opencode-ai/sdk'
packages:
- apps/*
- packages/*
- ee/apps/*
- ee/packages/*
catalog:
  react: 19.2.4
  react-dom: 19.2.4
catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
linkWorkspacePackages: true
preferWorkspacePackages: true
allowBuilds:
  '@whiskeysockets/baileys': true
  better-sqlite3: true
  electron: true
  esbuild: true
  msgpackr-extract: set this to true or false
  msw: false
  node-pty: true
  protobufjs: true
  sharp: true
overrides:
  protobufjs: latest
  seroval: latest
  react-router: latest
  next: latest
  fast-uri: latest
  fast-xml-parser: latest
  '@opentelemetry/sdk-node': latest
  '@opentelemetry/exporter-prometheus': latest
  defu: latest
  axios: latest
  tar: latest
  samlify: latest
  tmp: latest
  rollup: latest
  diff: latest
  yaml: latest
  ws: latest
  postcss: latest
  follow-redirects: latest
  qs: latest
  uuid: latest
  file-type: latest
  ip-address: latest
  esbuild: latest
  '@tootallnate/once': latest
  '@protobufjs/utf8': latest
  shell-quote: 1.8.4
