apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: zlinebot-alerts
  namespace: monitoring
spec:
  groups:
    - name: zlinebot.rules
      rules:
        - alert: HighCPU
          expr: rate(container_cpu_usage_seconds_total{namespace="zlinebot"}[1m]) > 0.8
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "High CPU usage detected"

        - alert: APIDown
          expr: up{namespace="zlinebot", service="api"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "API is down"
