apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: zlinebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:latest
          command:
            - redpanda
            - start
            - --overprovisioned
            - --smp=1
            - --memory=1G
            - --reserve-memory=0M
            - --node-id=0
            - --check=false
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: zlinebot
spec:
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
