apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: zlinebot
spec:
  replicas: 5
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: zlinebot-worker:latest
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: zlinebot-secret
