server_name: zeaz-nats
port: 4222
http_port: 8222

jetstream {
  store_dir: /data/jetstream
  max_mem_store: 1Gb
  max_file_store: 20Gb
}

accounts: {
  ZEAZ: {
    users: [
      {user: zeaz, password: $NATS_PASSWORD}
    ]
    jetstream: enabled
  }
}
system_account: ZEAZ
