#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/.env.full-local.example}"

cat > "$OUT" <<'EOF_ENV'
APP_NAME=zDash
APP_ENV=development
LOG_LEVEL=INFO
BACKEND_HOST=127.0.0.1
BACKEND_PORT=8005
FRONTEND_ORIGIN=http://127.0.0.1:5173
CORS_ALLOW_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,https://zdash.zeaz.dev
CORS_ALLOW_CREDENTIALS=false
DATABASE_URL=sqlite:///./zdash.db
REDIS_URL=redis://127.0.0.1:16380/0
DB_ECHO=false
DB_POOL_SIZE=5
DB_MAX_OVERFLOW=10

PRODUCTION_SAFETY_LOCK=true
PRODUCTION_ALLOW_LIVE_ACTIONS=false
AUTH_ENABLED=true
AUTH_ALLOW_BOOTSTRAP_IN_PRODUCTION=false
METRICS_AUTH_REQUIRED=false
METRICS_ALLOW_UNAUTHENTICATED_DEV=true
JWT_SECRET_KEY=dev-only-change-before-production
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_PASSWORD=dev-only-change-before-production
DEFAULT_ADMIN_PASSWORD=dev-only-change-before-production

TRADING_ENABLED=true
DRY_RUN=true
LIVE_TRADING_ACK=false
MT5_ENABLED=false
RISK_GUARDIAN_ENABLED=true
ALLOW_MANUAL_RESUME=true
REQUIRE_RESUME_REASON=true
HARD_HALT_ON_DAILY_DRAWDOWN=false

SCHEDULER_ENABLED=true
SCHEDULER_TIMEZONE=Asia/Bangkok
SCHEDULER_DEFAULT_MAX_RUNTIME_SECONDS=300
SCHEDULER_ALLOW_MANUAL_RUN=true
SCHEDULER_STORE=in_memory
FRIDAY_AGENT_ENABLED=true

BACKTESTING_ENABLED=true
BACKTEST_DATASET_SOURCE=mock
BACKTEST_DEFAULT_SYMBOL=XAUUSD
BACKTEST_DEFAULT_TIMEFRAME=M5
BACKTEST_INITIAL_BALANCE=10000
BACKTEST_DEFAULT_RISK_PER_TRADE_PERCENT=1
BACKTEST_COMMISSION_PER_TRADE=0
BACKTEST_SPREAD_POINTS=25
BACKTEST_SLIPPAGE_POINTS=5
PRIMARY_STRATEGY=ob_aggressive
ALLOW_STRATEGY_PROMOTION=false
OPTIMIZER_MAX_COMBINATIONS=100
OPTIMIZER_SORT_METRIC=profit_factor

AI_PROVIDER=mock
AI_TRADING_ANALYSIS_ENABLED=true
AI_TRADING_PROVIDER=mock
CONTENT_PIPELINE_ENABLED=true
CONTENT_STORE=in_memory
EDITOR_AGENT_ENABLED=true
GRAPHIC_AGENT_ENABLED=true
SOCIAL_AGENT_ENABLED=true
SOCIAL_PROVIDER=mock
SOCIAL_DRY_RUN=true
SOCIAL_APPROVAL_REQUIRED=true
SOCIAL_AUTO_POST_ENABLED=false
SOCIAL_REAL_POSTING_APPROVED=false

IOT_ENABLED=true
IOT_DRY_RUN=true
IOT_REQUIRE_CONFIRMATION=true
IOT_REAL_ACTIONS_APPROVED=false
MULTI_TENANT_ENABLED=true
REALTIME_ENABLED=true
REDIS_COLLAB_ENABLED=false
NOTIFICATIONS_ENABLED=true
NOTIFICATION_DRY_RUN=true
ALERT_RULES_ENABLED=true
EMAIL_NOTIFICATIONS_ENABLED=false
WEBHOOK_NOTIFICATIONS_ENABLED=false

CLOUDFLARE_ENABLED=true
CLOUDFLARE_DRY_RUN=true
CLOUDFLARE_TUNNEL_NAME=zdash
CLOUDFLARE_HOSTNAME=zdash.zeaz.dev
K8S_NAMESPACE=zdash
K8S_IMAGE_TAG=latest
RELEASE_CHANNEL=local
RELEASE_VERSION=local-full-feature-dry-run

MOBILE_API_ENABLED=true
PARTNER_API_ENABLED=true
DEVELOPER_PLATFORM_ENABLED=true
BILLING_ENABLED=true
BILLING_PROVIDER=mock
BILLING_CURRENCY=USD
BILLING_TRIAL_DAYS=14
BILLING_GRACE_PERIOD_DAYS=7
BILLING_FAIL_CLOSED=true
STRIPE_ENABLED=false
USAGE_METERING_ENABLED=true
USAGE_ENFORCEMENT_ENABLED=true
USAGE_RESET_MODE=monthly
MARKETPLACE_ENABLED=true
MARKETPLACE_INSTALL_ENABLED=true
MARKETPLACE_REVIEW_REQUIRED=true
PLUGIN_RUNTIME_MODE=sandbox
PLUGIN_ALLOW_EXTERNAL_NETWORK=false
PLUGIN_ALLOW_SECRET_ACCESS=false
ENTERPRISE_LICENSE_ENABLED=true
ENTERPRISE_OFFLINE_LICENSE_ENABLED=true
ENTERPRISE_EXPORT_ENABLED=true
ENTERPRISE_IMPORT_ENABLED=true
WHITE_LABEL_ENABLED=true
ONBOARDING_ENABLED=true
CUSTOMER_SUCCESS_ENABLED=true

SOVEREIGN_MODE_ENABLED=true
SOVEREIGN_FAIL_CLOSED=true
DEFAULT_DATA_REGION=local
ALLOWED_DATA_REGIONS=local,us,eu,apac
DATA_RESIDENCY_ENFORCEMENT_ENABLED=true
CROSS_REGION_SYNC_ENABLED=false
CROSS_REGION_SYNC_DRY_RUN=true
CUSTOMER_MANAGED_KEYS_ENABLED=true
KMS_PROVIDER=mock
KMS_DRY_RUN=true
EDGE_RUNNERS_ENABLED=true
EDGE_RUNNER_DRY_RUN=true
ONPREM_APPLIANCE_ENABLED=true
ONPREM_EXCLUDE_SECRETS=true
GLOBAL_OPS_ENABLED=true
GLOBAL_ROLLOUT_DRY_RUN=true
DIGITAL_TWIN_ENABLED=true
DIGITAL_TWIN_MODE=advisory
DIGITAL_TWIN_DRY_RUN=true
DIGITAL_TWIN_REQUIRE_EVIDENCE=true
MACRO_SIMULATION_ENABLED=true
MACRO_SIMULATION_DRY_RUN=true
CONTINUOUS_PLANNING_ENABLED=true
CONTINUOUS_PLANNING_MODE=advisory
CONTINUOUS_PLANNING_DRY_RUN=true
CONTINUOUS_PLANNING_REQUIRE_APPROVAL=true
STRATEGY_MEMORY_ENABLED=true
DECISION_LINEAGE_ENABLED=true
STRATEGIC_TRADEOFF_ENABLED=true
ROADMAP_SIMULATION_ENABLED=true
STRATEGY_WAR_ROOM_ENABLED=true
EOF_ENV

echo "Generated: $OUT"
echo "Safe mode: dry-run enabled, production safety lock enabled, live actions disabled."
