<?php
$all_bets = get_var('Bets');
$data = explode('+',$all_bets);
$echoStr = '';
$echoStr .=  "Black = <span class='pClass'>".$data[71]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Col bot = <span class='pClass'>".$data[137]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Col mid = <span class='pClass'>".$data[148]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Col top = <span class='pClass'>".$data[3]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 1 2 4 5 = <span class='pClass'>".$data[12]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 10 11 13 14 = <span class='pClass'>".$data[13]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 11 12 14 15 = <span class='pClass'>".$data[28]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 13 14 16 17 = <span class='pClass'>".$data[19]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 14 15 17 18 = <span class='pClass'>".$data[156]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 16 17 19 20 = <span class='pClass'>".$data[114]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 17 18 20 21 = <span class='pClass'>".$data[107]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 19 20 22 23 = <span class='pClass'>".$data[133]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 2 3 5 6 = <span class='pClass'>".$data[56]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 20 21 23 24 = <span class='pClass'>".$data[119]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 22 23 25 26 = <span class='pClass'>".$data[144]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 23 24 26 27 = <span class='pClass'>".$data[125]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 25 26 28 29 = <span class='pClass'>".$data[31]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 26 27 29 30 = <span class='pClass'>".$data[18]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 28 29 31 32 = <span class='pClass'>".$data[63]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 29 30 32 33 = <span class='pClass'>".$data[57]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 31 32 34 35 = <span class='pClass'>".$data[145]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 32 33 35 36 = <span class='pClass'>".$data[124]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 4 5 7 8 = <span class='pClass'>".$data[51]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 5 6 8 9 = <span class='pClass'>".$data[122]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 7 8 10 11 = <span class='pClass'>".$data[149]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Corner 8 9 11 12 = <span class='pClass'>".$data[111]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Even = <span class='pClass'>".$data[0]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 0 3 = <span class='pClass'>".$data[24]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 1 6 = <span class='pClass'>".$data[129]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 10 15 = <span class='pClass'>".$data[41]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 13 18 = <span class='pClass'>".$data[39]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 16 21 = <span class='pClass'>".$data[132]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 19 24 = <span class='pClass'>".$data[151]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 22 27 = <span class='pClass'>".$data[22]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 25 30 = <span class='pClass'>".$data[35]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 28 33 = <span class='pClass'>".$data[108]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 31 36 = <span class='pClass'>".$data[153]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 4 9 = <span class='pClass'>".$data[52]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Line 7 12 = <span class='pClass'>".$data[17]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr0 = <span class='pClass'>".$data[14]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr1 = <span class='pClass'>".$data[25]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr2 = <span class='pClass'>".$data[36]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr3 = <span class='pClass'>".$data[47]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr4 = <span class='pClass'>".$data[58]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr5 = <span class='pClass'>".$data[67]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr6 = <span class='pClass'>".$data[68]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr7 = <span class='pClass'>".$data[69]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr8 = <span class='pClass'>".$data[70]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr9 = <span class='pClass'>".$data[72]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr10 = <span class='pClass'>".$data[73]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr11 = <span class='pClass'>".$data[74]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr12 = <span class='pClass'>".$data[75]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr13 = <span class='pClass'>".$data[76]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr14 = <span class='pClass'>".$data[77]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr15 = <span class='pClass'>".$data[78]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr16 = <span class='pClass'>".$data[79]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr17 = <span class='pClass'>".$data[80]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr18 = <span class='pClass'>".$data[81]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr19 = <span class='pClass'>".$data[83]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr20 = <span class='pClass'>".$data[84]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr21 = <span class='pClass'>".$data[85]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr22 = <span class='pClass'>".$data[86]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr23 = <span class='pClass'>".$data[87]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr24 = <span class='pClass'>".$data[88]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr25 = <span class='pClass'>".$data[89]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr26 = <span class='pClass'>".$data[90]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr27 = <span class='pClass'>".$data[91]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr28 = <span class='pClass'>".$data[92]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr29 = <span class='pClass'>".$data[94]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr30 = <span class='pClass'>".$data[95]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr31 = <span class='pClass'>".$data[96]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr32 = <span class='pClass'>".$data[97]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr33 = <span class='pClass'>".$data[98]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr34 = <span class='pClass'>".$data[10]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr34 = <span class='pClass'>".$data[99]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr35 = <span class='pClass'>".$data[100]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nr36 = <span class='pClass'>".$data[101]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nrs1 12 = <span class='pClass'>".$data[104]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nrs1 18 = <span class='pClass'>".$data[82]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nrs13 24 = <span class='pClass'>".$data[115]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nrs19 36 = <span class='pClass'>".$data[93]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Nrs25 36 = <span class='pClass'>".$data[126]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Odd = <span class='pClass'>".$data[1]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Red = <span class='pClass'>".$data[2]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 0 1 = <span class='pClass'>".$data[65]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 0 2 = <span class='pClass'>".$data[15]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 0 3 = <span class='pClass'>".$data[29]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 1 2 = <span class='pClass'>".$data[54]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 1 4 = <span class='pClass'>".$data[45]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 10 11 = <span class='pClass'>".$data[135]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 10 13 = <span class='pClass'>".$data[61]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 11 12 = <span class='pClass'>".$data[16]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 11 14 = <span class='pClass'>".$data[9]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 12 15 = <span class='pClass'>".$data[102]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 13 14 = <span class='pClass'>".$data[143]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 13 16 = <span class='pClass'>".$data[23]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 14 15 = <span class='pClass'>".$data[117]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 14 17 = <span class='pClass'>".$data[11]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 15 18 = <span class='pClass'>".$data[154]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 16 17 = <span class='pClass'>".$data[42]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 16 19 = <span class='pClass'>".$data[123]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 17 18 = <span class='pClass'>".$data[40]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 17 20 = <span class='pClass'>".$data[37]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 18 21 = <span class='pClass'>".$data[157]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 19 20 = <span class='pClass'>".$data[5]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 19 22 = <span class='pClass'>".$data[142]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 2 3 = <span class='pClass'>".$data[103]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 2 5 = <span class='pClass'>".$data[116]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 20 21 = <span class='pClass'>".$data[155]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 20 23 = <span class='pClass'>".$data[134]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 21 24 = <span class='pClass'>".$data[46]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 22 23 = <span class='pClass'>".$data[21]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 22 25 = <span class='pClass'>".$data[152]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 23 24 = <span class='pClass'>".$data[7]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 23 26 = <span class='pClass'>".$data[141]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 24 27 = <span class='pClass'>".$data[118]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 25 26 = <span class='pClass'>".$data[106]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 25 28 = <span class='pClass'>".$data[38]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 26 27 = <span class='pClass'>".$data[105]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 26 29 = <span class='pClass'>".$data[59]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 27 30 = <span class='pClass'>".$data[26]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 28 29 = <span class='pClass'>".$data[49]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 28 31 = <span class='pClass'>".$data[131]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 29 30 = <span class='pClass'>".$data[44]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 29 32 = <span class='pClass'>".$data[60]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 3 6 = <span class='pClass'>".$data[27]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 30 33 = <span class='pClass'>".$data[55]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 31 32 = <span class='pClass'>".$data[112]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 31 34 = <span class='pClass'>".$data[140]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 32 33 = <span class='pClass'>".$data[109]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 32 35 = <span class='pClass'>".$data[130]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 33 36 = <span class='pClass'>".$data[138]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 34 35 = <span class='pClass'>".$data[158]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 35 36 = <span class='pClass'>".$data[146]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 4 5 = <span class='pClass'>".$data[120]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 4 7 = <span class='pClass'>".$data[33]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 5 6 = <span class='pClass'>".$data[43]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 5 8 = <span class='pClass'>".$data[6]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 6 9 = <span class='pClass'>".$data[62]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 7 10 = <span class='pClass'>".$data[4]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 7 8 = <span class='pClass'>".$data[64]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 8 11 = <span class='pClass'>".$data[139]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 8 9 = <span class='pClass'>".$data[48]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Split 9 12 = <span class='pClass'>".$data[147]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 0 1 2 = <span class='pClass'>".$data[8]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 0 2 3 = <span class='pClass'>".$data[127]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 1 2 3 = <span class='pClass'>".$data[136]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 10 11 12 = <span class='pClass'>".$data[30]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 13 14 15 = <span class='pClass'>".$data[150]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 16 17 18 = <span class='pClass'>".$data[53]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 19 20 21 = <span class='pClass'>".$data[20]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 22 23 24 = <span class='pClass'>".$data[128]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 25 26 27 = <span class='pClass'>".$data[113]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 28 29 30 = <span class='pClass'>".$data[50]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 31 32 33 = <span class='pClass'>".$data[121]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 34 35 36 = <span class='pClass'>".$data[32]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 4 5 6 = <span class='pClass'>".$data[34]." ".$_SESSION['currency']."</span><br />";
$echoStr .=  "Street 7 8 9 = <span class='pClass'>".$data[110]." ".$_SESSION['currency']."</span><br />";
$echoStr = str_replace('>0 '.$_SESSION['currency'],'><span class="zClass">0 '.$_SESSION['currency'].'</span>',$echoStr);
echo $echoStr;
?>