#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

ROOT="${PROJECT_ROOT:-}"
if [[ -z "$ROOT" ]]; then
  ROOT="$PWD"
  while [[ "$ROOT" != "/" ]]; do
    if [[ -d "$ROOT/.git" || -f "$ROOT/.env.example" || -f "$ROOT/Makefile" ]]; then
      break
    fi
    ROOT="$(dirname "$ROOT")"
  done
fi
[[ "$ROOT" != "/" ]] || ROOT="$PWD"
cd "$ROOT"

ENV_FILE="${ENV_FILE:-$ROOT/.env}"
NORMALIZER="$ROOT/scripts/cloudflare/clean-env-empty-values.sh"
BACKUP_DIR="${BACKUP_DIR:-$ROOT/.cloudflare-backups}"
PRIMARY_DOMAIN_DEFAULT="${PRIMARY_DOMAIN_DEFAULT:-zeaz.dev}"
mkdir -p "$BACKUP_DIR"

log(){ printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
die(){ log "ERROR: $*" >&2; exit 1; }

random_hex(){
  local bytes="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
  else
    head -c "$bytes" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

read_existing(){
  local key="$1"
  [[ -f "$ENV_FILE" ]] || return 0
  awk -F= -v k="$key" '$1 == k {v=$0; sub(/^[^=]*=/, "", v); gsub(/^"|"$/, "", v); print v}' "$ENV_FILE" | tail -n 1
}

read_existing_any(){
  local key value
  for key in "$@"; do
    value="$(read_existing "$key")"
    if [[ -n "$value" ]]; then
      printf '%s' "$value"
      return 0
    fi
  done
}

keep_or_default(){
  local key="$1" default="$2" existing
  existing="$(read_existing "$key")"
  if [[ -n "$existing" ]]; then
    printf '%s' "$existing"
  else
    printf '%s' "$default"
  fi
}

keep_alias_or_blank(){
  local canonical="$1" legacy="$2" value
  value="$(read_existing_any "$canonical" "$legacy")"
  printf '%s' "$value"
}

write_kv(){
  local key="$1" value="$2"
  printf '%s=%s\n' "$key" "$value" >> "$TMP_ENV"
}

write_preserved_or_blank(){
  local canonical="$1" legacy="$2"
  write_kv "$canonical" "$(keep_alias_or_blank "$canonical" "$legacy")"
}

normalize_env_file(){
  local file="$1"
  [[ -f "$file" ]] || return 0
  [[ -x "$NORMALIZER" ]] || die "missing executable env normalizer: $NORMALIZER"
  bash "$NORMALIZER" "$file"
  chmod 600 "$file"
}

if [[ -f "$ENV_FILE" ]]; then
  backup="$BACKUP_DIR/env.$(date -u +%Y%m%dT%H%M%SZ).bak"
  cp "$ENV_FILE" "$backup"
  chmod 600 "$backup" 2>/dev/null || true
  log "backup saved: $backup"
fi

TMP_ENV="$(mktemp "$ENV_FILE.all.XXXXXX")"
chmod 600 "$TMP_ENV"

cat > "$TMP_ENV" <<'HEADER'
# zeaz-platform complete Free/no-cost environment
# Generated by scripts/environments/generate-env-all.sh
#
# Do not commit this file. Keep chmod 600.
# Fill real Cloudflare IDs/tokens before running make validate-env-strict.

HEADER

write_kv "PRIMARY_DOMAIN" "$(keep_or_default PRIMARY_DOMAIN "$PRIMARY_DOMAIN_DEFAULT")"
write_kv "CLOUDFLARE_PLAN_TIER" "Free"
write_kv "COST_LOCK" "true"
write_kv "ALLOW_PAID_CLOUDFLARE_FEATURES" "false"
write_kv "ALLOW_R2_WRITE" "false"
write_kv "ALLOW_WORKERS_DEPLOY" "false"
write_kv "ALLOW_LOAD_BALANCING" "false"
write_kv "ALLOW_ADVANCED_WAF" "false"
write_kv "ALLOW_LOGPUSH" "false"
write_kv "ENVIRONMENT" "$(keep_or_default ENVIRONMENT dev)"
write_kv "REGION" "$(keep_or_default REGION ap-southeast-1)"
write_kv "ORIGIN_INFRA_TYPE" "$(keep_or_default ORIGIN_INFRA_TYPE vm)"
write_kv "ORIGIN_HOSTS" "$(keep_or_default ORIGIN_HOSTS app.internal,pay.internal)"
write_kv "TERRAFORM_BACKEND_TYPE" "local"
write_kv "TERRAFORM_STATE_BUCKET" ""
write_kv "TERRAFORM_LOCK_TABLE" ""
write_kv "SECRET_ROTATION_INTERVAL" "$(keep_or_default SECRET_ROTATION_INTERVAL 30d)"
write_kv "CLOUDFLARE_AI_GATEWAY_SLUG" "$(keep_alias_or_blank CLOUDFLARE_AI_GATEWAY_SLUG CLOUDFLARE_AI_GATEWAY_SLUG)"

cat >> "$TMP_ENV" <<'SECTION'

# Cloudflare account / zone IDs. Fill real values from Cloudflare Dashboard.
SECTION
write_preserved_or_blank "CLOUDFLARE_ACCOUNT_ID" "CLOUDFLARE_ACCOUNT_ID"
write_preserved_or_blank "CLOUDFLARE_ZONE_ID" "CLOUDFLARE_ZONE_ID"

cat >> "$TMP_ENV" <<'SECTION'

# Cloudflare tokens. Fill real scoped API tokens. Do not use legacy global key auth.
SECTION
write_preserved_or_blank "CLOUDFLARE_BOOTSTRAP_TOKEN" "CLOUDFLARE_BOOTSTRAP_TOKEN"
write_preserved_or_blank "CLOUDFLARE_API_TOKEN" "CLOUDFLARE_API_TOKEN"
write_preserved_or_blank "CLOUDFLARE_DNS_TOKEN" "CLOUDFLARE_DNS_TOKEN"
write_preserved_or_blank "CLOUDFLARE_WORKERS_TOKEN" "CLOUDFLARE_WORKERS_TOKEN"
write_preserved_or_blank "CLOUDFLARE_ZT_TOKEN" "CLOUDFLARE_ZT_TOKEN"
write_preserved_or_blank "CLOUDFLARE_WAF_TOKEN" "CLOUDFLARE_WAF_TOKEN"
write_preserved_or_blank "CLOUDFLARE_TUNNEL_TOKEN" "CLOUDFLARE_TUNNEL_TOKEN"
write_preserved_or_blank "CLOUDFLARE_R2_TOKEN" "CLOUDFLARE_R2_TOKEN"
write_preserved_or_blank "CLOUDFLARE_AUDIT_TOKEN" "CLOUDFLARE_AUDIT_TOKEN"
write_preserved_or_blank "CLOUDFLARE_AI_GATEWAY_TOKEN" "CLOUDFLARE_AI_GATEWAY_TOKEN"

cat >> "$TMP_ENV" <<'SECTION'

# Identity provider metadata for Cloudflare Access.
SECTION
write_kv "IDENTITY_PROVIDER_TYPE" "$(keep_or_default IDENTITY_PROVIDER_TYPE saml)"
write_kv "IDENTITY_PROVIDER_VENDOR" "$(keep_or_default IDENTITY_PROVIDER_VENDOR authentik)"
write_kv "IDENTITY_PROVIDER_METADATA_URL" "$(keep_or_default IDENTITY_PROVIDER_METADATA_URL https://auth.zeaz.dev/application/saml/cloudflare-zero-trust/metadata/)"

cat >> "$TMP_ENV" <<'SECTION'

# Local generated secrets. These are local-only placeholders and are safe to rotate.
SECTION
write_kv "SOPS_AGE_KEY" "$(keep_or_default SOPS_AGE_KEY "AGE-SECRET-KEY-$(random_hex 32)")"
write_kv "JWT_SECRET" "$(keep_or_default JWT_SECRET "$(random_hex 32)")"
write_kv "TOKEN_ENCRYPTION_KEY" "$(keep_or_default TOKEN_ENCRYPTION_KEY "$(random_hex 32)")"

cat >> "$TMP_ENV" <<'SECTION'

# Free control-panel local runtime defaults.
SECTION
write_kv "APP_NAME" "$(keep_or_default APP_NAME zcf-control-free)"
write_kv "APP_ENV" "$(keep_or_default APP_ENV production)"
write_kv "APP_URL" "$(keep_or_default APP_URL https://panel.zeaz.dev)"
write_kv "API_URL" "$(keep_or_default API_URL https://api.zeaz.dev)"
write_kv "DATABASE_URL" "$(keep_or_default DATABASE_URL sqlite:////data/zcf-control.db)"
write_kv "CLOUDFLARED_METRICS" "$(keep_or_default CLOUDFLARED_METRICS 127.0.0.1:20241)"
write_kv "LOG_LEVEL" "$(keep_or_default LOG_LEVEL info)"

normalize_env_file "$TMP_ENV"
mv "$TMP_ENV" "$ENV_FILE"
chmod 600 "$ENV_FILE"
normalize_env_file "$ENV_FILE"
log "wrote complete env template: $ENV_FILE"

cat <<'NEXT'

Next:
  1. Fill real Cloudflare IDs and scoped tokens in .env:
       CLOUDFLARE_ACCOUNT_ID
       CLOUDFLARE_ZONE_ID
       CLOUDFLARE_API_TOKEN
       CLOUDFLARE_DNS_TOKEN
       CLOUDFLARE_WORKERS_TOKEN
       CLOUDFLARE_ZT_TOKEN
       CLOUDFLARE_WAF_TOKEN
       CLOUDFLARE_TUNNEL_TOKEN
       CLOUDFLARE_R2_TOKEN
  2. Run source-health validation:
       make validate-env
  3. Run strict deployment validation after real values are filled:
       make validate-env-strict

The generator never creates fake Cloudflare tokens because that would make strict deployment validation unsafe.
NEXT
