apiVersion: v1
kind: ConfigMap
metadata:
  name: zeaz-genesis
  labels:
    app.kubernetes.io/name: zeaz-testnet
data:
  genesis.json: |
    {
      "protocol_id": "zeaz/1.0.0",
      "chain_id": "zeaz-testnet-k8s",
      "governance": { "quorum": 1 },
      "economic_policy": { "unit_of_account": "ZCREDIT", "min_stake": 0, "verification_quorum": 0 }
    }
