name: deploy-worker

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform validate

  deploy-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: terraform-validate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_WORKERS_TOKEN }}
