name: DR Testing
on: [workflow_dispatch]
jobs:
  dr-testing:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/restore.sh
        env:
          BACKUP_FILE: backup/latest.tar.gz
