name: SBOM Generation
on: [workflow_dispatch, push]
jobs:
  sbom:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Generate SBOM
        run: syft . -o spdx-json > sbom.spdx.json
